config/routes.rb
Wxm::Application.routes.draw do
  root "home#index"
  get "/not_weixin" => "home#not_weixin"
  get "/n" => "home#new_app"
  get "/a" => "home#allapps"
  get "/bl" => "home#wxlogin", as: "wxlogin"
  get "/ml/:redirection_url" => "home#mobilewxlogin", as: "mobilewxlogin", :constraints => { :redirection_url => /.*/ }
  get "/u" => "home#wxuser", as: "wxuser"
  get "/l" => "home#logout", as: "logout"
  get "/openinbrowser/:openid?red=:redirection" => "home#openinbrowser", as: "openinbrowser"
  resources :users

  get "/:appuid" => "home#mobileshow"

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
<%= logger.debug "FLASH MEASSAGE #{message}" %>
<div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
</div>
<% end %>

app/views/layouts/_left_menu.html.erb
<!-- 4. $MAIN_MENU =================================================================================

        Main menu

        Notes:
        * to make the menu item active, add a class 'active' to the <li>
          example: <li class="active">...</li>
        * multilevel submenu example:
            <li class="mm-dropdown">
              <a href="#"><span class="mm-text">Submenu item text 1</span></a>
              <ul>
                <li>...</li>
                <li class="mm-dropdown">
                  <a href="#"><span class="mm-text">Submenu item text 2</span></a>
                  <ul>
                    <li>...</li>
                    ...
                  </ul>
                </li>
                ...
              </ul>
            </li>
-->
    <div id="main-menu" role="navigation">
        <div id="main-menu-inner">
            <div class="menu-content top" id="menu-content-demo">
                <!-- Menu custom content demo
                     CSS:        styles/pixel-admin-less/demo.less or styles/pixel-admin-scss/_demo.scss
                     Javascript: html/assets/demo/demo.js
                 -->
                <div>
                    <div class="text-bg"><span class="text-slim"><%= t :welcome %>,</span> <span class="text-semibold"><%= current_user.nickname %></span></div>
                    <%= image_tag current_user.wx_headimgurl %>
                    <div class="btn-group">
                        <%= link_to logout_path, class: "btn btn-danger btn-outline dark" do %>
                        <i class="fa fa-power-off"></i>
                        <%= t :logout %>
                        <% end -%>
                    </div>
                    <a href="#" class="close">&times;</a>
                </div>
            </div>

            <ul class="navigation">
                <li>
                    <a href="/"><i class="menu-icon fa fa-dashboard"></i><span class="mm-text"><%= t :dashboard %></span><span class="label label-warning">Updated</span></a>
                </li>
                <li>
                <%= link_to a_path do  %>
                    <i class="menu-icon fa fa-list-ol"></i><span class="mm-text"><%=t :my_apps %></span>
                <% end -%>
                </li>
<!--
                <li class="mm-dropdown">
                    <a href="#"><i class="menu-icon fa fa-sitemap"></i><span class="mm-text">Menu levels</span><span class="badge badge-primary">6</span></a>
                    <ul>
                        <li>
                            <a tabindex="-1" href="#"><span class="mm-text">Menu level 1.1</span><span class="badge badge-danger">12</span><span class="label label-info">21</span></a>
                        </li>
                        <li>
                            <a tabindex="-1" href="#"><span class="mm-text">Menu level 1.2</span></a>
                        </li>
                        <li class="mm-dropdown">
                            <a tabindex="-1" href="#"><span class="mm-text">Menu level 1.3</span><span class="label label-warning">5</span></a>
                            <ul>
                                <li>
                                    <a tabindex="-1" href="#"><span class="mm-text">Menu level 2.1</span></a>
                                </li>
                                <li class="mm-dropdown">
                                    <a tabindex="-1" href="#"><span class="mm-text">Menu level 2.2</span></a>
                                    <ul>
                                        <li class="mm-dropdown">
                                            <a tabindex="-1" href="#"><span class="mm-text">Menu level 3.1</span></a>
                                            <ul>
                                                <li>
                                                    <a tabindex="-1" href="#"><span class="mm-text">Menu level 4.1</span></a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a tabindex="-1" href="#"><span class="mm-text">Menu level 3.2</span></a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a tabindex="-1" href="#"><span class="mm-text">Menu level 2.2</span></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
-->
            </ul> <!-- / .navigation -->
            <div class="menu-content">
                <%= link_to n_url, class: "btn btn-success btn-labeled" do %>
                    <i class="btn-label icon fa fa-plus"></i>
                    <%= t :new_app %>
                <% end -%>
            </div>
        </div> <!-- / #main-menu-inner -->
    </div> <!-- / #main-menu -->
<!-- /4. $MAIN_MENU -->

app/views/layouts/_main_nav.html.erb
<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
    <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

    <div class="navbar-inner">
        <div class="navbar-header">

            <%= link_to root_url, class:  "navbar-brand" do %>
                <img alt="Pixel Admin" src="<%= asset_path 'favicon.png' %>" width="18px" height="18px">
                WXM.IO

            <% end -%>
        </div>

        <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>wxm.io</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="icon" type="image/x-icon" href="<%= asset_path 'favicon.png' %>" />
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>

<body class="theme-default main-menu-animated">

<div id="main-wrapper">


<%= render 'layouts/main_nav' %>

<% if not current_user.nil? %>
<%= render 'layouts/left_menu' %>
<% end %>

    <div id="content-wrapper">
      <%= render partial: "layouts/flash_messages", flash: flash %>
    <%= yield %>
    <% if Rails.env.development? %>

    <div class="qrcode">
        <img src="<%= asset_path @qr.image.url %>" alt="qrcode" />
    </div>

    <% end -%>
    </div> <!-- / #content-wrapper -->
    <div id="main-menu-bg"></div>
</div> <!-- / #main-wrapper -->

<%= javascript_include_tag "application" %>
<script>
<!--
    var init = [];

    init.push(function () {
        // Javascript code here
    });

    window.PixelAdmin.start(init);

    // TODO: Add a loading page to check if is wechat
    // function wxJsBridgeReady(readyCallback) {
    //     if (readyCallback && typeof readyCallback == 'function') {
    //         var Api = this;
    //         var wxReadyFunc = function () {
    //             readyCallback(Api);
    //         };
    //         if (typeof window.WeixinJSBridge == "undefined"){
    //             if (document.addEventListener) {
    //                 document.addEventListener('WeixinJSBridgeReady', wxReadyFunc, false);
    //             } else if (document.attachEvent) {
    //                 document.attachEvent('WeixinJSBridgeReady', wxReadyFunc);
    //                 document.attachEvent('onWeixinJSBridgeReady', wxReadyFunc);
    //             }
    //         }else{
    //             wxReadyFunc();
    //         }
    //     }
    // }

    // wxJsBridgeReady(function(){
    //   alert(typeof window.WeixinJSBridge);
    // });
// -->
</script>
<%= yield :javascripts %>
</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield :title %></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-title" content="<%= yield :title %>">
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <meta name="apple-touch-fullscreen" content="yes">
        <%= yield :meta %>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="HandheldFriendly" content="true">
        <meta name="MobileOptimized" content="width">
        <meta name="format-detection" content="telephone=no">
        <%= yield :stylesheets %>
    </head>
    <body>
        <% if current_user %>
        <script>
        window.currentUser = <%= raw current_user.to_json %>;
        </script>
        <% end %>
        <%= yield %>
        <%= yield :javascripts %>
    </body>
</html>